# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='data.user',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nuser.proto\x12\tdata.user\"\x14\n\x04Time\x12\x0c\n\x04time\x18\x01 \x01(\x03\"1\n\x0cStudyingWord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rstudied_count\x18\x02 \x01(\x05\"/\n\x0bTestingWord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cpassed_count\x18\x02 \x01(\x05\"&\n\tWordOrder\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05order\x18\x02 \x01(\x05\"\xb1\x06\n\x04User\x12*\n\x11last_signing_time\x18\x01 \x01(\x0b\x32\x0f.data.user.Time\x12\x18\n\x10today_study_date\x18\x02 \x01(\x05\x12\x1c\n\x14last_studied_word_id\x18\x03 \x01(\x05\x12:\n\x0estudying_words\x18\x04 \x03(\x0b\x32\".data.user.User.StudyingWordsEntry\x12\x38\n\rtesting_words\x18\x05 \x03(\x0b\x32!.data.user.User.TestingWordsEntry\x12\x45\n\x14studying_word_orders\x18\x06 \x03(\x0b\x32\'.data.user.User.StudyingWordOrdersEntry\x12\x43\n\x13testing_word_orders\x18\x07 \x03(\x0b\x32&.data.user.User.TestingWordOrdersEntry\x12\"\n\x1atoday_studying_words_index\x18\x08 \x01(\x05\x12\x1f\n\x17today_studying_word_ids\x18\t \x03(\x05\x12!\n\x19today_testing_words_index\x18\n \x01(\x05\x12\x1e\n\x16today_testing_word_ids\x18\x0b \x03(\x05\x1aM\n\x12StudyingWordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.data.user.StudyingWord:\x02\x38\x01\x1aK\n\x11TestingWordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.data.user.TestingWord:\x02\x38\x01\x1aO\n\x17StudyingWordOrdersEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.data.user.WordOrder:\x02\x38\x01\x1aN\n\x16TestingWordOrdersEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.data.user.WordOrder:\x02\x38\x01\x62\x06proto3')
)




_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='data.user.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='data.user.Time.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=45,
)


_STUDYINGWORD = _descriptor.Descriptor(
  name='StudyingWord',
  full_name='data.user.StudyingWord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='data.user.StudyingWord.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='studied_count', full_name='data.user.StudyingWord.studied_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=96,
)


_TESTINGWORD = _descriptor.Descriptor(
  name='TestingWord',
  full_name='data.user.TestingWord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='data.user.TestingWord.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passed_count', full_name='data.user.TestingWord.passed_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=145,
)


_WORDORDER = _descriptor.Descriptor(
  name='WordOrder',
  full_name='data.user.WordOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='data.user.WordOrder.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order', full_name='data.user.WordOrder.order', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=185,
)


_USER_STUDYINGWORDSENTRY = _descriptor.Descriptor(
  name='StudyingWordsEntry',
  full_name='data.user.User.StudyingWordsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='data.user.User.StudyingWordsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='data.user.User.StudyingWordsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=690,
  serialized_end=767,
)

_USER_TESTINGWORDSENTRY = _descriptor.Descriptor(
  name='TestingWordsEntry',
  full_name='data.user.User.TestingWordsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='data.user.User.TestingWordsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='data.user.User.TestingWordsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=769,
  serialized_end=844,
)

_USER_STUDYINGWORDORDERSENTRY = _descriptor.Descriptor(
  name='StudyingWordOrdersEntry',
  full_name='data.user.User.StudyingWordOrdersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='data.user.User.StudyingWordOrdersEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='data.user.User.StudyingWordOrdersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=846,
  serialized_end=925,
)

_USER_TESTINGWORDORDERSENTRY = _descriptor.Descriptor(
  name='TestingWordOrdersEntry',
  full_name='data.user.User.TestingWordOrdersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='data.user.User.TestingWordOrdersEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='data.user.User.TestingWordOrdersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=927,
  serialized_end=1005,
)

_USER = _descriptor.Descriptor(
  name='User',
  full_name='data.user.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_signing_time', full_name='data.user.User.last_signing_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='today_study_date', full_name='data.user.User.today_study_date', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_studied_word_id', full_name='data.user.User.last_studied_word_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='studying_words', full_name='data.user.User.studying_words', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testing_words', full_name='data.user.User.testing_words', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='studying_word_orders', full_name='data.user.User.studying_word_orders', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testing_word_orders', full_name='data.user.User.testing_word_orders', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='today_studying_words_index', full_name='data.user.User.today_studying_words_index', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='today_studying_word_ids', full_name='data.user.User.today_studying_word_ids', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='today_testing_words_index', full_name='data.user.User.today_testing_words_index', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='today_testing_word_ids', full_name='data.user.User.today_testing_word_ids', index=10,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_USER_STUDYINGWORDSENTRY, _USER_TESTINGWORDSENTRY, _USER_STUDYINGWORDORDERSENTRY, _USER_TESTINGWORDORDERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=1005,
)

_USER_STUDYINGWORDSENTRY.fields_by_name['value'].message_type = _STUDYINGWORD
_USER_STUDYINGWORDSENTRY.containing_type = _USER
_USER_TESTINGWORDSENTRY.fields_by_name['value'].message_type = _TESTINGWORD
_USER_TESTINGWORDSENTRY.containing_type = _USER
_USER_STUDYINGWORDORDERSENTRY.fields_by_name['value'].message_type = _WORDORDER
_USER_STUDYINGWORDORDERSENTRY.containing_type = _USER
_USER_TESTINGWORDORDERSENTRY.fields_by_name['value'].message_type = _WORDORDER
_USER_TESTINGWORDORDERSENTRY.containing_type = _USER
_USER.fields_by_name['last_signing_time'].message_type = _TIME
_USER.fields_by_name['studying_words'].message_type = _USER_STUDYINGWORDSENTRY
_USER.fields_by_name['testing_words'].message_type = _USER_TESTINGWORDSENTRY
_USER.fields_by_name['studying_word_orders'].message_type = _USER_STUDYINGWORDORDERSENTRY
_USER.fields_by_name['testing_word_orders'].message_type = _USER_TESTINGWORDORDERSENTRY
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.message_types_by_name['StudyingWord'] = _STUDYINGWORD
DESCRIPTOR.message_types_by_name['TestingWord'] = _TESTINGWORD
DESCRIPTOR.message_types_by_name['WordOrder'] = _WORDORDER
DESCRIPTOR.message_types_by_name['User'] = _USER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:data.user.Time)
  })
_sym_db.RegisterMessage(Time)

StudyingWord = _reflection.GeneratedProtocolMessageType('StudyingWord', (_message.Message,), {
  'DESCRIPTOR' : _STUDYINGWORD,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:data.user.StudyingWord)
  })
_sym_db.RegisterMessage(StudyingWord)

TestingWord = _reflection.GeneratedProtocolMessageType('TestingWord', (_message.Message,), {
  'DESCRIPTOR' : _TESTINGWORD,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:data.user.TestingWord)
  })
_sym_db.RegisterMessage(TestingWord)

WordOrder = _reflection.GeneratedProtocolMessageType('WordOrder', (_message.Message,), {
  'DESCRIPTOR' : _WORDORDER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:data.user.WordOrder)
  })
_sym_db.RegisterMessage(WordOrder)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {

  'StudyingWordsEntry' : _reflection.GeneratedProtocolMessageType('StudyingWordsEntry', (_message.Message,), {
    'DESCRIPTOR' : _USER_STUDYINGWORDSENTRY,
    '__module__' : 'user_pb2'
    # @@protoc_insertion_point(class_scope:data.user.User.StudyingWordsEntry)
    })
  ,

  'TestingWordsEntry' : _reflection.GeneratedProtocolMessageType('TestingWordsEntry', (_message.Message,), {
    'DESCRIPTOR' : _USER_TESTINGWORDSENTRY,
    '__module__' : 'user_pb2'
    # @@protoc_insertion_point(class_scope:data.user.User.TestingWordsEntry)
    })
  ,

  'StudyingWordOrdersEntry' : _reflection.GeneratedProtocolMessageType('StudyingWordOrdersEntry', (_message.Message,), {
    'DESCRIPTOR' : _USER_STUDYINGWORDORDERSENTRY,
    '__module__' : 'user_pb2'
    # @@protoc_insertion_point(class_scope:data.user.User.StudyingWordOrdersEntry)
    })
  ,

  'TestingWordOrdersEntry' : _reflection.GeneratedProtocolMessageType('TestingWordOrdersEntry', (_message.Message,), {
    'DESCRIPTOR' : _USER_TESTINGWORDORDERSENTRY,
    '__module__' : 'user_pb2'
    # @@protoc_insertion_point(class_scope:data.user.User.TestingWordOrdersEntry)
    })
  ,
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:data.user.User)
  })
_sym_db.RegisterMessage(User)
_sym_db.RegisterMessage(User.StudyingWordsEntry)
_sym_db.RegisterMessage(User.TestingWordsEntry)
_sym_db.RegisterMessage(User.StudyingWordOrdersEntry)
_sym_db.RegisterMessage(User.TestingWordOrdersEntry)


_USER_STUDYINGWORDSENTRY._options = None
_USER_TESTINGWORDSENTRY._options = None
_USER_STUDYINGWORDORDERSENTRY._options = None
_USER_TESTINGWORDORDERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
