# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: word.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='word.proto',
  package='data.word',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nword.proto\x12\tdata.word\"G\n\x04Word\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08spelling\x18\x02 \x01(\t\x12\x0f\n\x07meaning\x18\x03 \x01(\t\x12\x10\n\x08meaning2\x18\x04 \x01(\t\"r\n\x05Words\x12*\n\x05words\x18\x01 \x03(\x0b\x32\x1b.data.word.Words.WordsEntry\x1a=\n\nWordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.data.word.Word:\x02\x38\x01\x62\x06proto3')
)




_WORD = _descriptor.Descriptor(
  name='Word',
  full_name='data.word.Word',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='data.word.Word.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spelling', full_name='data.word.Word.spelling', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meaning', full_name='data.word.Word.meaning', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meaning2', full_name='data.word.Word.meaning2', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=96,
)


_WORDS_WORDSENTRY = _descriptor.Descriptor(
  name='WordsEntry',
  full_name='data.word.Words.WordsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='data.word.Words.WordsEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='data.word.Words.WordsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=212,
)

_WORDS = _descriptor.Descriptor(
  name='Words',
  full_name='data.word.Words',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='data.word.Words.words', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_WORDS_WORDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=212,
)

_WORDS_WORDSENTRY.fields_by_name['value'].message_type = _WORD
_WORDS_WORDSENTRY.containing_type = _WORDS
_WORDS.fields_by_name['words'].message_type = _WORDS_WORDSENTRY
DESCRIPTOR.message_types_by_name['Word'] = _WORD
DESCRIPTOR.message_types_by_name['Words'] = _WORDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Word = _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), {
  'DESCRIPTOR' : _WORD,
  '__module__' : 'word_pb2'
  # @@protoc_insertion_point(class_scope:data.word.Word)
  })
_sym_db.RegisterMessage(Word)

Words = _reflection.GeneratedProtocolMessageType('Words', (_message.Message,), {

  'WordsEntry' : _reflection.GeneratedProtocolMessageType('WordsEntry', (_message.Message,), {
    'DESCRIPTOR' : _WORDS_WORDSENTRY,
    '__module__' : 'word_pb2'
    # @@protoc_insertion_point(class_scope:data.word.Words.WordsEntry)
    })
  ,
  'DESCRIPTOR' : _WORDS,
  '__module__' : 'word_pb2'
  # @@protoc_insertion_point(class_scope:data.word.Words)
  })
_sym_db.RegisterMessage(Words)
_sym_db.RegisterMessage(Words.WordsEntry)


_WORDS_WORDSENTRY._options = None
# @@protoc_insertion_point(module_scope)
