# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sign_pb2 as sign__pb2


class SignStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SignIn = channel.unary_unary(
        '/service.sign.Sign/SignIn',
        request_serializer=sign__pb2.SignInRequest.SerializeToString,
        response_deserializer=sign__pb2.SignInResponse.FromString,
        )


class SignServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SignIn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SignServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SignIn': grpc.unary_unary_rpc_method_handler(
          servicer.SignIn,
          request_deserializer=sign__pb2.SignInRequest.FromString,
          response_serializer=sign__pb2.SignInResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'service.sign.Sign', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
