# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sign.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entities_pb2 as entities__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sign.proto',
  package='service.sign',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nsign.proto\x12\x0cservice.sign\x1a\x0e\x65ntities.proto\" \n\rSignInRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"6\n\x0eSignInResponse\x12$\n\x04user\x18\x01 \x01(\x0b\x32\x16.service.entities.User2M\n\x04Sign\x12\x45\n\x06SignIn\x12\x1b.service.sign.SignInRequest\x1a\x1c.service.sign.SignInResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[entities__pb2.DESCRIPTOR,])




_SIGNINREQUEST = _descriptor.Descriptor(
  name='SignInRequest',
  full_name='service.sign.SignInRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='service.sign.SignInRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=76,
)


_SIGNINRESPONSE = _descriptor.Descriptor(
  name='SignInResponse',
  full_name='service.sign.SignInResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='service.sign.SignInResponse.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=132,
)

_SIGNINRESPONSE.fields_by_name['user'].message_type = entities__pb2._USER
DESCRIPTOR.message_types_by_name['SignInRequest'] = _SIGNINREQUEST
DESCRIPTOR.message_types_by_name['SignInResponse'] = _SIGNINRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignInRequest = _reflection.GeneratedProtocolMessageType('SignInRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNINREQUEST,
  '__module__' : 'sign_pb2'
  # @@protoc_insertion_point(class_scope:service.sign.SignInRequest)
  })
_sym_db.RegisterMessage(SignInRequest)

SignInResponse = _reflection.GeneratedProtocolMessageType('SignInResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNINRESPONSE,
  '__module__' : 'sign_pb2'
  # @@protoc_insertion_point(class_scope:service.sign.SignInResponse)
  })
_sym_db.RegisterMessage(SignInResponse)



_SIGN = _descriptor.ServiceDescriptor(
  name='Sign',
  full_name='service.sign.Sign',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=134,
  serialized_end=211,
  methods=[
  _descriptor.MethodDescriptor(
    name='SignIn',
    full_name='service.sign.Sign.SignIn',
    index=0,
    containing_service=None,
    input_type=_SIGNINREQUEST,
    output_type=_SIGNINRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIGN)

DESCRIPTOR.services_by_name['Sign'] = _SIGN

# @@protoc_insertion_point(module_scope)
