# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import study_pb2 as study__pb2


class StudyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MoveToPreviousWord = channel.unary_unary(
        '/service.study.Study/MoveToPreviousWord',
        request_serializer=study__pb2.MoveToPreviousWordRequest.SerializeToString,
        response_deserializer=study__pb2.MoveToPreviousWordResponse.FromString,
        )
    self.MoveToNextWord = channel.unary_unary(
        '/service.study.Study/MoveToNextWord',
        request_serializer=study__pb2.MoveToNextWordRequest.SerializeToString,
        response_deserializer=study__pb2.MoveToNextWordResponse.FromString,
        )


class StudyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def MoveToPreviousWord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MoveToNextWord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StudyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MoveToPreviousWord': grpc.unary_unary_rpc_method_handler(
          servicer.MoveToPreviousWord,
          request_deserializer=study__pb2.MoveToPreviousWordRequest.FromString,
          response_serializer=study__pb2.MoveToPreviousWordResponse.SerializeToString,
      ),
      'MoveToNextWord': grpc.unary_unary_rpc_method_handler(
          servicer.MoveToNextWord,
          request_deserializer=study__pb2.MoveToNextWordRequest.FromString,
          response_serializer=study__pb2.MoveToNextWordResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'service.study.Study', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
