#!/bin/bash

function auto-generate-all() {
    pushd $AUTOGENERATEDIR

    # remove all files
    find . ! -name '__init__.py' -type f -exec trash {} +

    # re-generate grpc files
    python3 -m grpc_tools.protoc --proto_path=$PROTODIR \
        --python_out=. --grpc_python_out=. \
        $PROTODIR/*.proto

    popd
}

BASEDIR="$(cd "$(dirname "$0")"; pwd)"
PROTODIR="$BASEDIR/../eva_proto"
AUTOGENERATEDIR="$BASEDIR/../eva/protocol/grpc_auto_generated"

case "$1" in
    auto-generate-all)
        auto-generate-all
        ;;
    *)
        echo "invalid"
        ;;
esac
